import os
from dotenv import load_dotenv

load_dotenv()

class Config:
    SECRET_KEY = os.environ.get('SECRET_KEY') or 'hard-to-guess-string'
    SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URL') or 'sqlite:///quotepro.db'
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY')
    MYPOS_SESSION_API_URL = os.environ.get('MYPOS_SESSION_API_URL')
    MYPOS_OAUTH_API_URL = os.environ.get('MYPOS_OAUTH_API_URL')
    MYPOS_PAYMENT_API_URL = os.environ.get('MYPOS_PAYMENT_API_URL')
    MYPOS_TRANSACTION_API_LIST_URL = os.environ.get('MYPOS_TRANSACTION_API_LIST_URL')
    PARTNER_ID = os.environ.get('PARTNER_ID')
    APP_ANALYTICS_APPLICATION_ID = os.environ.get('APP_ANALYTICS_APPLICATION_ID')
    ECOMMERCE_APPLICATION_ID = os.environ.get('ECOMMERCE_APPLICATION_ID')
    APP_ANALYTICS_PARTNER_CLIENT_ID = os.environ.get('APP_ANALYTICS_PARTNER_CLIENT_ID')
    APP_ANALYTICS_PARTNER_CLIENT_SECRET = os.environ.get('APP_ANALYTICS_PARTNER_CLIENT_SECRET')
    APP_ANALYTICS_MERCHANT_CLIENT_ID = os.environ.get('APP_ANALYTICS_MERCHANT_CLIENT_ID')
    APP_ANALYTICS_MERCHANT_CLIENT_SECRET = os.environ.get('APP_ANALYTICS_MERCHANT_CLIENT_SECRET')
    ECOMMERCE_PARTNER_CLIENT_ID = os.environ.get('ECOMMERCE_PARTNER_CLIENT_ID')
    ECOMMERCE_PARTNER_CLIENT_SECRET = os.environ.get('ECOMMERCE_PARTNER_CLIENT_SECRET')
    ECOMMERCE_MERCHANT_CLIENT_ID = os.environ.get('ECOMMERCE_MERCHANT_CLIENT_ID')
    ECOMMERCE_MERCHANT_CLIENT_SECRET = os.environ.get('ECOMMERCE_MERCHANT_CLIENT_SECRET')



